# ワークフロー定義の開始
main:
    steps:
    # 初期設定ステップ
    - init:
        assign:
        - repository: projects/${PROJECT_ID}/locations/${REPOSITORY_LOCATION}/repositories/${REPOSITORY_ID}a

    # Cloud Function の実行ステップ
    - callCloudFunction:
        call: http.get
        args:
            url: "${CLOUD_FUNCTION_ENDPOINT_URL}"
            auth:
                type: OIDC
    # Dataform のコンパイル処理
    - createCompilationResult:
        call: http.post
        args:
            url: "https://dataform.googleapis.com/v1beta1/projects/${PROJECT_ID}/locations/${REPOSITORY_LOCATION}/repositories/${REPOSITORY_ID}/compilationResults"
            body:
                gitCommitish: GIT_COMMITISH
        result: compilationResult

    # Dataform ワークフローの実行処理
    - createWorkflowInvocation:
        call: http.post
        args:
            url: "https://dataform.googleapis.com/v1beta1/projects/${PROJECT_ID}/locations/${REPOSITORY_LOCATION}/repositories/${REPOSITORY_ID}/workflowInvocations"
            body:
                compilationResult: "$${compilationResult.body.name}"