projectId: dev-dbd
bucketName: kenkoukazoku-rawdata
backupBucketName: kenkoukazoku-rawdata-backup
targets:
 - path: test
   fileSearchPath: test
   fieldDelimiter: ","
   fileEncoding: "utf-8"
   dataset: rawdata
   tableName: test123
   isMaster: false
   schema: 
    - name: test_id
      type: STRING
      mode: REQUIRED
    - name: age
      type: INTEGER
      mode: NULLABLE
      